### ISSUE TITLE
Add instructions how to build on windows OS

### ISSUE THREAD

**Issue by OWarneke** [PLCnext/MqttClient#3]
Building locally with the shell scripts written for Linux on a windows system might be troublesome.

1. you will need git to clone the dependencies
2. You need a bash to execute the scripts
3. You need symlink support.
4. you need the plcncli. (PLCnCLI_Win64_2019.0) phoenixcontact.com -> AXCF2152 -> Downloads -> Software
5. you need the SDK (SDK_WIN64_2019.3)  phoenixcontact.com -> AXCF2152 -> Downloads -> Software

**Comment by OWarneke** [comment]
Possible platform independent solution:
integrate build scripts content into CMakeLists

**Comment by martinboers** [comment]
Closing in favour of the more genral issue #7 .
