### ISSUE TITLE
Use default path of Toolchain

### ISSUE THREAD

**Issue by markusgraube** [PLCnext/MqttClient#4]
The installation instructions does not use the default installation path of the SDK which is `/opt/pxc/2019.3`

**Comment by OWarneke** [comment]
This would help getting started faster.

**Comment by markusgraube** [comment]
Yeah, it would just be great if you can just copy the commands and start. No need for looking for correct paths

**Comment by martinboers** [comment]
Closing in favour of the more general issue at #7.
