### ISSUE TITLE
Headstart for including Paho during compiling

### ISSUE THREAD

**Issue by markusgraube** [PLCnext/MqttClient#6]
Can you give me some hints how to integrate paho c lib and paho c++ lib during manual compilation?
The provided installation instructions are not sufficient for me.

I am using a Ubuntu system and have installed  the paho-wqtt libs both for c and c++ (probably with the wrong version).
I stop at this step: 
```
cmake -G "Ninja" -DCMAKE_TOOLCHAIN_FILE=/opt/pxc/2019.3/toolchain.cmake -DBUILD_TESTING=OFF -DUSE_ARP_DEVICE=ON -DCMAKE_STAGING_PREFIX=/home/tcs-user/Documents/projects/MqttClient/bin/axcf2152 -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DARP_TOOLCHAIN_ROOT=/opt/pxc/2019.3 -DARP_DEVICE=AXCF2152 "-DARP_DEVICE_VERSION=2019.3 (19.3.0.18509  )" -S . -B ./build/axcf2152-2019.3 
-- Boost version: 1.63.0
-- Found the following Boost libraries:
--   regex
CMake Error at CMakeLists.txt:12 (_find_package):
  Could not find a configuration file for package "PahoMqttCpp" that is
  compatible with requested version "".

  The following configuration files were considered but not accepted:

    /usr/local/lib/cmake/PahoMqttCpp/PahoMqttCppConfig.cmake, version: 1.0.1 (64bit)

Call Stack (most recent call first):
  libs/MqttClientService/CMakeLists.txt:50 (find_package)
```

**Comment by OWarneke** [comment]
Hello Markus,
this looks like paho can not be found.
where did you install it?
Is it available in your prefix path?

When you clone this Repository you can use the scripts available in the "tools" folder for compiling.
This should setup everything accordingly.

how to call the scripts you can  see in the gitlab-ci.yaml file.
kind regards,
Oliver

**Comment by markusgraube** [comment]
Finally, I get it working. I just have forgotten to install the paho libs correctly.

However, you may update your instructions a little bit:

1. Some of the CMake-Variables are not used at all. So you can leave them out (as CMake als suggests). These are for example: `USE_ARP_DEVICE`

2. When installing the lib, it was not clear to me that both `libPxceTcs.Mqtt.Client.so` and `libs/MqttClientService/intermediate/config/MqttClient.acf.config` can be found on the source directory and not the build directory
